"""
mk_session.py
=============
MK Intel — Session State Model

This is the spine of the entire MK Intel pipeline.
Every phase reads from and writes to a MKSession object.

A session represents one complete analysis run:
    one company → one OBJ → N SOBJs → M TAWs per SOBJ

Design principles:
    - Every field has a clear owner (which phase writes it)
    - Status enum prevents phases from running out of order
    - All fields are serializable to JSON (no custom objects)
    - Confidence flows through: company → OBJ → SOBJs → TAWs
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional
import json
import uuid


# ── Status lifecycle ──────────────────────────────────────────────────────────

class SessionStatus(str, Enum):
    """
    Linear lifecycle. Each status unlocks the next phase.
    A session can only move forward, never backward.
    """
    CREATED             = "created"             # session initialized
    COMPANY_IDENTIFIED  = "company_identified"  # business summary ready
    OBJ_SET             = "obj_set"             # objective validated
    SOBJS_APPROVED      = "sobjs_approved"      # all SOBJs confirmed by user
    DATA_INGESTED       = "data_ingested"       # proprietary data processed (optional)
    TAAWS_GENERATED     = "taaws_generated"     # all TAWs produced and scored
    COMPLETED           = "completed"           # final output delivered


# ── Sub-objects ───────────────────────────────────────────────────────────────

@dataclass
class CompanyProfile:
    """
    Output of Phase 1 — company intelligence step.
    Written by: web scraper / LLM business summary call.
    """
    name:               str
    url:                Optional[str]           = None
    description_input:  Optional[str]           = None  # user-provided if no web presence
    business_summary:   Optional[str]           = None  # LLM-generated synthesis
    industry:           Optional[str]           = None  # inferred industry category
    value_proposition:  Optional[str]           = None  # what they sell / offer
    customer_type:      Optional[str]           = None  # B2C / B2B / mixed
    source:             Optional[str]           = None  # "web_scrape" | "user_input"
    confidence:         str                     = "low" # low / medium / high
    raw_web_content:    Optional[str]           = None  # raw scraped text, kept for audit


@dataclass
class Objective:
    """
    The strategic OBJ. Validated against doctrine: Verb + Object, no audience.
    Written by: OBJ input + validation step (Phase 2.1 equivalent).
    """
    id:                 str
    statement:          str                     # e.g. "Reduce premium subscription churn"
    verb:               Optional[str]           = None  # extracted: "Reduce"
    object:             Optional[str]           = None  # extracted: "premium subscription churn"
    is_validated:       bool                    = False # passed Verb+Object check
    validation_notes:   Optional[str]           = None  # why it failed if is_validated=False
    original_input:     Optional[str]           = None  # what user actually typed before reframe


@dataclass
class SupportingObjective:
    """
    One SOBJ. Generated by LLM, approved/amended by user.
    Written by: SOBJ generation step (Phase 2.1).
    """
    id:                 str                     # e.g. "SOBJ-01"
    statement:          str                     # e.g. "[TA] renews subscription at billing cycle"
    direction:          str                     # increase/decrease/maintain/initiate/stop
    status:             str                     = "pending"  # pending / approved / amend_requested
    amendment_note:     Optional[str]           = None  # user's correction instruction
    version:            int                     = 1     # increments on each regeneration
    generated_by:       str                     = "llm"


@dataclass
class ProprietaryDataset:
    """
    Company-uploaded behavioral data. Optional — pipeline works without it.
    Written by: data ingestion step (Phase 1.2 / 1.3).
    """
    uploaded_files:     list[str]               = field(default_factory=list)  # filenames
    normalized:         bool                    = False
    segment_mapping:    Optional[dict]          = None  # {customer_id: segment_id}
    behavioral_signals: Optional[dict]          = None  # {segment_id: {signal: value}}
    coverage_stats:     Optional[dict]          = None  # how many customers mapped per segment
    ingest_notes:       Optional[str]           = None  # warnings, gaps, quality flags
    confidence:         str                     = "low" # low / medium / high based on coverage


@dataclass
class ScoredTA:
    """
    One scored (TA, SOBJ) pair — the output of the scoring algorithm.
    Written by: TAAW generation + scoring step (Phase 3).
    """
    ta_id:              str                     # e.g. "PAS_00"
    sobj_id:            str                     # e.g. "SOBJ-01"
    archetype_name:     str
    rank:               Optional[int]           = None
    final_score:        Optional[float]         = None
    composite_score:    Optional[float]         = None
    dimension_scores:   dict                    = field(default_factory=dict)
    size_modifier:      float                   = 1.0
    gate_passed:        bool                    = True
    gate_failure_reason:Optional[str]           = None
    recommendation:     Optional[str]           = None  # plain-language priority note
    taaw:               Optional[dict]          = None  # full TAAW JSON (schema v2)
    taaw_confidence:    str                     = "low" # low/medium/high — data vs baseline only
    generated_at:       Optional[str]           = None  # ISO timestamp


@dataclass
class SOBJResult:
    """
    All scored TAs for one SOBJ — the per-SOBJ output bundle.
    Written by: scoring + ranking step.
    """
    sobj_id:            str
    sobj_statement:     str
    ranked_tas:         list[ScoredTA]          = field(default_factory=list)
    disqualified_tas:   list[ScoredTA]          = field(default_factory=list)
    top_ta:             Optional[str]           = None  # segment_id of rank 1
    generated_at:       Optional[str]           = None


# ── Main session object ───────────────────────────────────────────────────────

@dataclass
class MKSession:
    """
    The spine of MK Intel. One session = one complete analysis run.

    Lifecycle:
        CREATED → COMPANY_IDENTIFIED → OBJ_SET → SOBJS_APPROVED
        → DATA_INGESTED (optional) → TAAWS_GENERATED → COMPLETED

    Usage:
        session = MKSession.new()
        session.company = CompanyProfile(name="Peloton", url="peloton.com")
        session.status = SessionStatus.COMPANY_IDENTIFIED
        session.save("/path/to/sessions/")
    """
    session_id:         str
    status:             SessionStatus
    created_at:         str
    updated_at:         str

    # Phase outputs — each written by a specific pipeline step
    company:            Optional[CompanyProfile]        = None  # Phase 1 step 1
    objective:          Optional[Objective]             = None  # Phase 1 step 2
    sobjs:              list[SupportingObjective]       = field(default_factory=list)  # Phase 1 step 3
    proprietary_data:   Optional[ProprietaryDataset]    = None  # Phase 1 step 4 (optional)
    sobj_results:       list[SOBJResult]                = field(default_factory=list)  # Phase 3

    # Session-level metadata
    analyst_notes:      Optional[str]                   = None
    error_log:          list[str]                       = field(default_factory=list)


    # ── Constructors ──────────────────────────────────────────────────────────

    @classmethod
    def new(cls) -> MKSession:
        """Create a fresh session."""
        now = datetime.now(timezone.utc).isoformat()
        return cls(
            session_id=str(uuid.uuid4()),
            status=SessionStatus.CREATED,
            created_at=now,
            updated_at=now,
        )

    @classmethod
    def from_dict(cls, data: dict) -> MKSession:
        """Deserialize from a saved JSON dict."""
        session = cls(
            session_id=data["session_id"],
            status=SessionStatus(data["status"]),
            created_at=data["created_at"],
            updated_at=data["updated_at"],
            analyst_notes=data.get("analyst_notes"),
            error_log=data.get("error_log", []),
        )
        if data.get("company"):
            session.company = CompanyProfile(**data["company"])
        if data.get("objective"):
            session.objective = Objective(**data["objective"])
        if data.get("sobjs"):
            session.sobjs = [SupportingObjective(**s) for s in data["sobjs"]]
        if data.get("proprietary_data"):
            session.proprietary_data = ProprietaryDataset(**data["proprietary_data"])
        if data.get("sobj_results"):
            for sr in data["sobj_results"]:
                ranked = [ScoredTA(**t) for t in sr.get("ranked_tas", [])]
                disq   = [ScoredTA(**t) for t in sr.get("disqualified_tas", [])]
                session.sobj_results.append(SOBJResult(
                    sobj_id=sr["sobj_id"],
                    sobj_statement=sr["sobj_statement"],
                    ranked_tas=ranked,
                    disqualified_tas=disq,
                    top_ta=sr.get("top_ta"),
                    generated_at=sr.get("generated_at"),
                ))
        return session


    # ── Status management ─────────────────────────────────────────────────────

    def advance(self, to_status: SessionStatus) -> None:
        """
        Move the session to the next status.
        Raises ValueError if the transition is not valid.
        """
        valid_transitions = {
            SessionStatus.CREATED:            SessionStatus.COMPANY_IDENTIFIED,
            SessionStatus.COMPANY_IDENTIFIED: SessionStatus.OBJ_SET,
            SessionStatus.OBJ_SET:            SessionStatus.SOBJS_APPROVED,
            SessionStatus.SOBJS_APPROVED:     SessionStatus.DATA_INGESTED,
            SessionStatus.DATA_INGESTED:      SessionStatus.TAAWS_GENERATED,
            SessionStatus.TAAWS_GENERATED:    SessionStatus.COMPLETED,
            # skip data ingestion if no proprietary data
            # handled by skip_data_ingestion()
        }
        expected = valid_transitions.get(self.status)
        if to_status != expected:
            raise ValueError(
                f"Invalid transition: {self.status} → {to_status}. "
                f"Expected next status: {expected}"
            )
        self.status = to_status
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def skip_data_ingestion(self) -> None:
        """
        Advance from SOBJS_APPROVED directly to TAAWS_GENERATED
        when no proprietary data is available.
        Sets a baseline-only flag on the session.
        """
        if self.status != SessionStatus.SOBJS_APPROVED:
            raise ValueError(
                f"Can only skip data ingestion from SOBJS_APPROVED. "
                f"Current status: {self.status}"
            )
        self.proprietary_data = ProprietaryDataset(
            ingest_notes="No proprietary data provided. Analysis uses baseline segments only.",
            confidence="low",
        )
        self.status = SessionStatus.TAAWS_GENERATED
        self.updated_at = datetime.now(timezone.utc).isoformat()


    # ── Convenience accessors ─────────────────────────────────────────────────

    def get_approved_sobjs(self) -> list[SupportingObjective]:
        return [s for s in self.sobjs if s.status == "approved"]

    def get_pending_sobjs(self) -> list[SupportingObjective]:
        return [s for s in self.sobjs if s.status == "pending"]

    def get_result_for_sobj(self, sobj_id: str) -> Optional[SOBJResult]:
        for r in self.sobj_results:
            if r.sobj_id == sobj_id:
                return r
        return None

    def all_sobjs_approved(self) -> bool:
        return len(self.sobjs) > 0 and all(s.status == "approved" for s in self.sobjs)

    def log_error(self, msg: str) -> None:
        self.error_log.append(f"{datetime.now(timezone.utc).isoformat()} — {msg}")
        self.updated_at = datetime.now(timezone.utc).isoformat()


    # ── Serialization ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        """Serialize to a plain dict — safe for JSON storage."""
        from dataclasses import asdict
        d = asdict(self)
        d["status"] = self.status.value
        return d

    def save(self, directory: str) -> str:
        """
        Persist session to a JSON file.
        Filename: {session_id}.json
        Returns the full file path.
        """
        from pathlib import Path
        path = Path(directory)
        path.mkdir(parents=True, exist_ok=True)
        filepath = path / f"{self.session_id}.json"
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, default=str)
        return str(filepath)

    @classmethod
    def load(cls, filepath: str) -> MKSession:
        """Load a session from a saved JSON file."""
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        return cls.from_dict(data)

    def summary(self) -> str:
        """Quick human-readable summary for debugging."""
        lines = [
            f"Session:  {self.session_id}",
            f"Status:   {self.status.value}",
            f"Company:  {self.company.name if self.company else '—'}",
            f"OBJ:      {self.objective.statement if self.objective else '—'}",
            f"SOBJs:    {len(self.sobjs)} ({len(self.get_approved_sobjs())} approved)",
            f"Results:  {len(self.sobj_results)} SOBJ(s) scored",
            f"Updated:  {self.updated_at}",
        ]
        return "\n".join(lines)


# ── Example usage (run this file directly to verify) ─────────────────────────

if __name__ == "__main__":

    # 1. Create a new session
    session = MKSession.new()
    print("Created session:")
    print(session.summary())
    print()

    # 2. Company identified
    session.company = CompanyProfile(
        name="Peloton",
        url="https://www.onepeloton.com",
        business_summary="Peloton sells connected fitness equipment and subscriptions.",
        industry="Consumer fitness / SaaS",
        customer_type="B2C",
        source="web_scrape",
        confidence="high",
    )
    session.advance(SessionStatus.COMPANY_IDENTIFIED)

    # 3. OBJ set
    session.objective = Objective(
        id="OBJ-01",
        statement="Reduce premium subscription churn",
        verb="Reduce",
        object="premium subscription churn",
        is_validated=True,
    )
    session.advance(SessionStatus.OBJ_SET)

    # 4. SOBJs generated and approved
    session.sobjs = [
        SupportingObjective(
            id="SOBJ-01",
            statement="[TA] renews subscription at next billing cycle",
            direction="increase",
            status="approved",
        ),
        SupportingObjective(
            id="SOBJ-02",
            statement="[TA] increases weekly workout frequency",
            direction="increase",
            status="approved",
        ),
    ]
    session.advance(SessionStatus.SOBJS_APPROVED)

    print("After SOBJs approved:")
    print(session.summary())
    print()
    print(f"All SOBJs approved: {session.all_sobjs_approved()}")
    print(f"Approved SOBJs: {[s.id for s in session.get_approved_sobjs()]}")
    print()

    # 5. Skip data ingestion (no proprietary data)
    session.skip_data_ingestion()

    # 6. Save to disk
    path = session.save("/tmp/mk_sessions")
    print(f"Session saved to: {path}")

    # 7. Reload and verify
    reloaded = MKSession.load(path)
    print(f"Reloaded session status: {reloaded.status.value}")
    print(f"Reloaded company: {reloaded.company.name}")
